name: SimpleWebApi Build Pipeline
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Cheking Out Code
      uses: actions/checkout@v2
    - name: Seting Up .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.306
        include-prerelease: false
    - name: Restoring Nuget Packages
      run: dotnet restore
    - name: Building Project
      run: dotnet build --no-restore
    - name: Running Tests
      run: dotnet test --no-build --verbosity normal
